import perfectionist from "eslint-plugin-perfectionist"
import { defineConfig, type DummyRuleMap } from "oxlint"

const { rules: perfectionistRules } = perfectionist.configs["recommended-natural"]

export default defineConfig({
    categories: {
        correctness: "error",
    },
    env: {
        builtin: true,
        es2026: true,
        node: true,
    },
    extends: [{ rules: perfectionistRules as DummyRuleMap }],
    ignorePatterns: [".gitignore", "dist/**", "node_modules/**"],
    jsPlugins: [
        {
            name: "perfectionist",
            specifier: "eslint-plugin-perfectionist",
        },
    ],
    options: {
        typeAware: true,
        typeCheck: true,
    },
    plugins: ["typescript", "unicorn"],
    rules: {
        "constructor-super": "error",
        "for-direction": "error",
        "getter-return": "error",
        "no-array-constructor": "error",
        "no-async-promise-executor": "error",
        "no-case-declarations": "error",
        "no-class-assign": "error",
        "no-compare-neg-zero": "error",
        "no-cond-assign": "error",
        "no-const-assign": "error",
        "no-constant-binary-expression": "error",
        "no-constant-condition": "error",
        "no-control-regex": "error",
        "no-debugger": "error",
        "no-delete-var": "error",
        "no-dupe-class-members": "error",
        "no-dupe-else-if": "error",
        "no-dupe-keys": "error",
        "no-duplicate-case": "error",
        "no-empty": "error",
        "no-empty-character-class": "error",
        "no-empty-function": "error",
        "no-empty-pattern": "error",
        "no-empty-static-block": "error",
        "no-ex-assign": "error",
        "no-extra-boolean-cast": "error",
        "no-fallthrough": "error",
        "no-func-assign": "error",
        "no-global-assign": "error",
        "no-import-assign": "error",
        "no-invalid-regexp": "error",
        "no-irregular-whitespace": "error",
        "no-loss-of-precision": "error",
        "no-misleading-character-class": "error",
        "no-new-native-nonconstructor": "error",
        "no-nonoctal-decimal-escape": "error",
        "no-obj-calls": "error",
        "no-prototype-builtins": "error",
        "no-redeclare": "error",
        "no-regex-spaces": "error",
        "no-self-assign": "error",
        "no-setter-return": "error",
        "no-shadow-restricted-names": "error",
        "no-sparse-arrays": "error",
        "no-this-before-super": "error",
        "no-unassigned-vars": "error",
        "no-undef": "error",
        "no-unreachable": "error",
        "no-unsafe-finally": "error",
        "no-unsafe-negation": "error",
        "no-unsafe-optional-chaining": "error",
        "no-unused-expressions": "error",
        "no-unused-labels": "error",
        "no-unused-private-class-members": "error",
        "no-unused-vars": "error",
        "no-useless-assignment": "error",
        "no-useless-backreference": "error",
        "no-useless-catch": "error",
        "no-useless-constructor": "error",
        "no-useless-escape": "error",
        "no-with": "error",
        "perfectionist/sort-classes": [
            "error",
            {
                customGroups: [
                    {
                        elementNamePattern:
                            "^(onModuleInit|onApplicationBootstrap|onModuleDestroy|beforeApplicationShutdown|onApplicationShutdown)$",
                        groupName: "nestjs-lifecycle-methods",
                    },
                ],
                groups: [
                    "index-signature",
                    ["static-property", "static-accessor-property"],
                    ["static-get-method", "static-set-method"],
                    ["protected-static-property", "protected-static-accessor-property"],
                    ["protected-static-get-method", "protected-static-set-method"],
                    ["private-static-property", "private-static-accessor-property"],
                    ["private-static-get-method", "private-static-set-method"],
                    "static-block",
                    ["property", "accessor-property"],
                    ["get-method", "set-method"],
                    ["protected-property", "protected-accessor-property"],
                    ["protected-get-method", "protected-set-method"],
                    ["readonly-property"],
                    ["private-property", "private-accessor-property"],
                    ["private-get-method", "private-set-method"],
                    "constructor",
                    "nestjs-lifecycle-methods",
                    ["static-method", "static-function-property"],
                    ["protected-static-method", "protected-static-function-property"],
                    ["private-static-method", "private-static-function-property"],
                    ["method", "function-property"],
                    ["protected-method", "protected-function-property"],
                    ["private-method", "private-function-property"],
                    "unknown",
                ],
            },
        ],
        "perfectionist/sort-imports": [
            "error",
            {
                internalPattern: ["^@/.+"],
            },
        ],
        "preserve-caught-error": "error",
        "require-yield": "error",
        "typescript/adjacent-overload-signatures": "error",
        "typescript/array-type": "error",
        "typescript/await-thenable": "error",
        "typescript/ban-ts-comment": [
            "error",
            {
                minimumDescriptionLength: 10,
            },
        ],
        "typescript/ban-tslint-comment": "error",
        "typescript/class-literal-property-style": "error",
        "typescript/consistent-generic-constructors": "error",
        "typescript/consistent-indexed-object-style": "error",
        "typescript/consistent-type-assertions": "error",
        "typescript/consistent-type-definitions": "error",
        "typescript/dot-notation": "error",
        "typescript/no-array-delete": "error",
        "typescript/no-base-to-string": "error",
        "typescript/no-confusing-non-null-assertion": "error",
        "typescript/no-confusing-void-expression": "error",
        "typescript/no-deprecated": "error",
        "typescript/no-duplicate-enum-values": "error",
        "typescript/no-duplicate-type-constituents": "error",
        "typescript/no-dynamic-delete": "error",
        "typescript/no-empty-object-type": "error",
        "typescript/no-explicit-any": "error",
        "typescript/no-extra-non-null-assertion": "error",
        "typescript/no-extraneous-class": [
            "error",
            {
                allowWithDecorator: true,
            },
        ],
        "typescript/no-floating-promises": "error",
        "typescript/no-for-in-array": "error",
        "typescript/no-implied-eval": "error",
        "typescript/no-inferrable-types": "error",
        "typescript/no-invalid-void-type": "error",
        "typescript/no-meaningless-void-operator": "error",
        "typescript/no-misused-new": "error",
        "typescript/no-misused-promises": "error",
        "typescript/no-misused-spread": "error",
        "typescript/no-mixed-enums": "error",
        "typescript/no-namespace": "error",
        "typescript/no-non-null-asserted-nullish-coalescing": "error",
        "typescript/no-non-null-asserted-optional-chain": "error",
        "typescript/no-non-null-assertion": "error",
        "typescript/no-redundant-type-constituents": "error",
        "typescript/no-require-imports": "error",
        "typescript/no-this-alias": "error",
        "typescript/no-unnecessary-boolean-literal-compare": "error",
        "typescript/no-unnecessary-condition": "error",
        "typescript/no-unnecessary-template-expression": "error",
        "typescript/no-unnecessary-type-arguments": "error",
        "typescript/no-unnecessary-type-assertion": "error",
        "typescript/no-unnecessary-type-constraint": "error",
        "typescript/no-unnecessary-type-conversion": "error",
        "typescript/no-unnecessary-type-parameters": "error",
        "typescript/no-unsafe-argument": "error",
        "typescript/no-unsafe-assignment": "error",
        "typescript/no-unsafe-call": "error",
        "typescript/no-unsafe-declaration-merging": "error",
        "typescript/no-unsafe-enum-comparison": "error",
        "typescript/no-unsafe-function-type": "error",
        "typescript/no-unsafe-member-access": "error",
        "typescript/no-unsafe-return": "error",
        "typescript/no-unsafe-unary-minus": "error",
        "typescript/no-useless-default-assignment": "error",
        "typescript/no-wrapper-object-types": "error",
        "typescript/non-nullable-type-assertion-style": "error",
        "typescript/only-throw-error": "error",
        "typescript/prefer-as-const": "error",
        "typescript/prefer-find": "error",
        "typescript/prefer-for-of": "error",
        "typescript/prefer-function-type": "error",
        "typescript/prefer-includes": "error",
        "typescript/prefer-literal-enum-member": "error",
        "typescript/prefer-namespace-keyword": "error",
        "typescript/prefer-nullish-coalescing": "error",
        "typescript/prefer-optional-chain": "error",
        "typescript/prefer-promise-reject-errors": "error",
        "typescript/prefer-reduce-type-parameter": "error",
        "typescript/prefer-regexp-exec": "error",
        "typescript/prefer-return-this-type": "error",
        "typescript/prefer-string-starts-ends-with": "error",
        "typescript/related-getter-setter-pairs": "error",
        "typescript/require-await": "error",
        "typescript/restrict-plus-operands": [
            "error",
            {
                allowAny: false,
                allowBoolean: false,
                allowNullish: false,
                allowNumberAndString: false,
                allowRegExp: false,
            },
        ],
        "typescript/restrict-template-expressions": [
            "error",
            {
                allowAny: true,
                allowBoolean: false,
                allowNever: false,
                allowNullish: true,
                allowNumber: true,
                allowRegExp: false,
            },
        ],
        "typescript/return-await": ["error", "error-handling-correctness-only"],
        "typescript/triple-slash-reference": "error",
        "typescript/unbound-method": "error",
        "typescript/unified-signatures": "error",
        "typescript/use-unknown-in-catch-callback-variable": "error",
        "unicorn/catch-error-name": "error",
        "unicorn/consistent-assert": "error",
        "unicorn/consistent-date-clone": "error",
        "unicorn/consistent-empty-array-spread": "error",
        "unicorn/consistent-existence-index-check": "error",
        "unicorn/consistent-function-scoping": "error",
        "unicorn/consistent-template-literal-escape": "error",
        "unicorn/error-message": "error",
        "unicorn/escape-case": "error",
        "unicorn/explicit-length-check": "error",
        "unicorn/explicit-timer-delay": "error",
        "unicorn/filename-case": "error",
        "unicorn/import-style": "error",
        "unicorn/max-nested-calls": "error",
        "unicorn/new-for-builtins": "error",
        "unicorn/no-abusive-eslint-disable": "error",
        "unicorn/no-accessor-recursion": "error",
        "unicorn/no-anonymous-default-export": "error",
        "unicorn/no-array-callback-reference": "error",
        "unicorn/no-array-fill-with-reference-type": "error",
        "unicorn/no-array-method-this-argument": "error",
        "unicorn/no-array-reduce": "error",
        "unicorn/no-array-reverse": "error",
        "unicorn/no-array-sort": "error",
        "unicorn/no-await-expression-member": "error",
        "unicorn/no-await-in-promise-methods": "error",
        "unicorn/no-confusing-array-with": "error",
        "unicorn/no-console-spaces": "error",
        "unicorn/no-document-cookie": "error",
        "unicorn/no-empty-file": "error",
        "unicorn/no-immediate-mutation": "error",
        "unicorn/no-instanceof-builtins": "error",
        "unicorn/no-invalid-fetch-options": "error",
        "unicorn/no-invalid-remove-event-listener": "error",
        "unicorn/no-lonely-if": "error",
        "unicorn/no-magic-array-flat-depth": "error",
        "unicorn/no-negated-condition": "error",
        "unicorn/no-negation-in-equality-check": "error",
        "unicorn/no-new-array": "error",
        "unicorn/no-new-buffer": "error",
        "unicorn/no-null": "error",
        "unicorn/no-object-as-default-parameter": "error",
        "unicorn/no-process-exit": "error",
        "unicorn/no-single-promise-in-promise-methods": "error",
        "unicorn/no-static-only-class": "error",
        "unicorn/no-thenable": "error",
        "unicorn/no-this-assignment": "error",
        "unicorn/no-typeof-undefined": "error",
        "unicorn/no-unnecessary-array-flat-depth": "error",
        "unicorn/no-unnecessary-array-splice-count": "error",
        "unicorn/no-unnecessary-await": "error",
        "unicorn/no-unnecessary-slice-end": "error",
        "unicorn/no-unreadable-array-destructuring": "error",
        "unicorn/no-unreadable-iife": "error",
        "unicorn/no-useless-collection-argument": "error",
        "unicorn/no-useless-error-capture-stack-trace": "error",
        "unicorn/no-useless-fallback-in-spread": "error",
        "unicorn/no-useless-iterator-to-array": "error",
        "unicorn/no-useless-length-check": "error",
        "unicorn/no-useless-promise-resolve-reject": "error",
        "unicorn/no-useless-spread": "error",
        "unicorn/no-useless-switch-case": "error",
        "unicorn/no-useless-undefined": "error",
        "unicorn/no-zero-fractions": "error",
        "unicorn/numeric-separators-style": "error",
        "unicorn/prefer-add-event-listener": "error",
        "unicorn/prefer-array-find": "error",
        "unicorn/prefer-array-flat": "error",
        "unicorn/prefer-array-flat-map": "error",
        "unicorn/prefer-array-index-of": "error",
        "unicorn/prefer-array-some": "error",
        "unicorn/prefer-at": "error",
        "unicorn/prefer-bigint-literals": "error",
        "unicorn/prefer-blob-reading-methods": "error",
        "unicorn/prefer-class-fields": "error",
        "unicorn/prefer-classlist-toggle": "error",
        "unicorn/prefer-code-point": "error",
        "unicorn/prefer-date-now": "error",
        "unicorn/prefer-default-parameters": "error",
        "unicorn/prefer-dom-node-append": "error",
        "unicorn/prefer-dom-node-remove": "error",
        "unicorn/prefer-dom-node-text-content": "error",
        "unicorn/prefer-event-target": "error",
        "unicorn/prefer-export-from": "error",
        "unicorn/prefer-global-this": "error",
        "unicorn/prefer-includes": "error",
        "unicorn/prefer-keyboard-event-key": "error",
        "unicorn/prefer-logical-operator-over-ternary": "error",
        "unicorn/prefer-math-min-max": "error",
        "unicorn/prefer-math-trunc": "error",
        "unicorn/prefer-modern-dom-apis": "error",
        "unicorn/prefer-modern-math-apis": "error",
        "unicorn/prefer-module": "error",
        "unicorn/prefer-native-coercion-functions": "error",
        "unicorn/prefer-negative-index": "error",
        "unicorn/prefer-node-protocol": "error",
        "unicorn/prefer-number-coercion": "error",
        "unicorn/prefer-number-properties": "error",
        "unicorn/prefer-object-from-entries": "error",
        "unicorn/prefer-optional-catch-binding": "error",
        "unicorn/prefer-prototype-methods": "error",
        "unicorn/prefer-query-selector": "error",
        "unicorn/prefer-reflect-apply": "error",
        "unicorn/prefer-regexp-test": "error",
        "unicorn/prefer-response-static-json": "error",
        "unicorn/prefer-set-has": "error",
        "unicorn/prefer-set-size": "error",
        "unicorn/prefer-single-call": "error",
        "unicorn/prefer-spread": "error",
        "unicorn/prefer-string-raw": "error",
        "unicorn/prefer-string-replace-all": "error",
        "unicorn/prefer-string-slice": "error",
        "unicorn/prefer-string-starts-ends-with": "error",
        "unicorn/prefer-string-trim-start-end": "error",
        "unicorn/prefer-structured-clone": "error",
        "unicorn/prefer-ternary": "error",
        "unicorn/prefer-top-level-await": "error",
        "unicorn/prefer-type-error": "error",
        "unicorn/relative-url-style": "error",
        "unicorn/require-array-join-separator": "error",
        "unicorn/require-module-attributes": "error",
        "unicorn/require-module-specifiers": "error",
        "unicorn/require-number-to-fixed-digits-argument": "error",
        "unicorn/switch-case-braces": "error",
        "unicorn/switch-case-break-position": "error",
        "unicorn/text-encoding-identifier-case": "error",
        "unicorn/throw-new-error": "error",
        "use-isnan": "error",
        "valid-typeof": "error",
    },
})
