/**
 * Barrel generation for the package entry points.
 *
 * - `fv-common/<name>` re-exports every module below `src/<name>/` (see {@link subpathEntryNames}).
 * - `fv-common` re-exports every remaining module.
 *
 * Barrels consist solely of `export * from` statements, which forward values and types alike, so no AST analysis is
 * required. Default exports are not forwarded.
 *
 * Name clashes within one entry point are reported as TS2308 by the type check only; the bundler drops clashing names
 * silently. The build therefore runs this script before the type-aware lint step.
 *
 * Usage: `node scripts/barrels.ts`
 */
import { glob, readFile, writeFile } from "node:fs/promises"
import path from "node:path"

const mainEntryName = "index"
export const subpathEntryNames: ReadonlySet<string> = new Set(["na", "node", "trading"])
export const entryNames: ReadonlySet<string> = new Set([mainEntryName, ...subpathEntryNames])

const sourceDirectory = path.resolve(import.meta.dirname, "../src")
const barrelHeader = "// Generated by scripts/barrels.ts. Do not edit.\n\n"
const moduleExcludePatterns = ["**/*.d.ts", "**/*.test.ts", ...[...entryNames].map((name) => `${name}.ts`)]
const naturalCollator = new Intl.Collator("en", { numeric: true })

const toPosixPath = (filePath: string): string => filePath.split(path.sep).join(path.posix.sep)

const getEntryName = (modulePath: string): string => {
    const [topLevelSegment = ""] = modulePath.split(path.posix.sep)
    return subpathEntryNames.has(topLevelSegment) ? topLevelSegment : mainEntryName
}

const toExportStatement = (modulePath: string): string => `export * from "./${modulePath.replace(/\.ts$/, ".js")}"\n`

const getEntryPath = (entryName: string): string => path.join(sourceDirectory, `${entryName}.ts`)

/**
 * Writes `content` to `filePath` unless the file already holds it, so unchanged barrels keep their timestamps and do
 * not trigger watchers.
 *
 * @returns Whether the file has been written.
 */
const writeIfChanged = async (filePath: string, content: string): Promise<boolean> => {
    const currentContent = await readFile(filePath, "utf8").catch(() => undefined)
    if (currentContent === content) return false

    await writeFile(filePath, content)
    return true
}

const writeBarrel = async (entryName: string, modulePaths: readonly string[]): Promise<void> => {
    const barrelPath = getEntryPath(entryName)
    const content = barrelHeader + modulePaths.map(toExportStatement).join("")
    const hasChanged = await writeIfChanged(barrelPath, content)

    if (hasChanged)
        console.info(`Barrel updated: ${path.relative(process.cwd(), barrelPath)} (${modulePaths.length} modules)`)
}

/** Regenerates `src/<entry>.ts` for every entry point. */
export const writeBarrels = async (): Promise<void> => {
    const modulePaths = await Array.fromAsync(glob("**/*.ts", { cwd: sourceDirectory, exclude: moduleExcludePatterns }))
    const modulesByEntry = Map.groupBy(modulePaths.map(toPosixPath).toSorted(naturalCollator.compare), getEntryName)

    await Promise.all([...entryNames].map((entryName) => writeBarrel(entryName, modulesByEntry.get(entryName) ?? [])))
}

/** Absolute entry file paths, keyed by output name. */
export const entryFiles: Readonly<Record<string, string>> = Object.fromEntries(
    [...entryNames].map((entryName) => [entryName, getEntryPath(entryName)]),
)

if (import.meta.main) await writeBarrels()
