import { writeFile } from "atomically"
import path from "node:path"
import { fileURLToPath } from "node:url"
import { Project, SourceFile, SyntaxKind } from "ts-morph"

import type { BarrelCategory } from "./barrel-categories.types.js"

import { simpleStringSort } from "../src/sort.js"
import categoriesJson from "./barrel-categories.json" with { type: "json" }

const barrelCategories = categoriesJson as BarrelCategory[]

const sourceDirectory = fileURLToPath(new URL("../src", import.meta.url))

const isDryRun = process.argv.includes("--dry-run")
const targetArgument = process.argv.find((argument) => argument.startsWith("--target="))?.split("=", 2)[1]

const filename = path.basename(import.meta.filename)
const header = `//
// Auto-generated by scripts/${filename}
// Do not edit this file directly
//
`

const categories = barrelCategories.map((category) => ({
    ...category,
    absDir: path.resolve(sourceDirectory, category.dir),
    barrelPath: path.resolve(sourceDirectory, `${category.name}.ts`),
}))

const mainBarrelPath = path.resolve(sourceDirectory, "index.ts")
const allBarrelPaths = new Set([mainBarrelPath, ...categories.map((c) => c.barrelPath)])

const isRuntimeValueKind = (kind: SyntaxKind): boolean => {
    switch (kind) {
        case SyntaxKind.ClassDeclaration:
        case SyntaxKind.EnumDeclaration:
        case SyntaxKind.FunctionDeclaration:
        case SyntaxKind.ModuleDeclaration:
        case SyntaxKind.VariableDeclaration: {
            return true
        }
        case SyntaxKind.InterfaceDeclaration:
        case SyntaxKind.TypeAliasDeclaration: {
            return false
        }
        default: {
            return true
        }
    }
}

const isInDir = (filePath: string, dir: string): boolean => {
    const relative = path.relative(dir, filePath)
    return relative === "" || (!relative.startsWith("..") && !path.isAbsolute(relative))
}

const normalizeRelativePath = (filePath: string): string => {
    const relative = path.relative(sourceDirectory, filePath).replaceAll("\\", "/")
    return `./${relative.replace(/\.ts$/, ".js")}`
}

const analyzeFileExports = (file: SourceFile) => {
    const values: string[] = []
    const types: string[] = []

    for (const symbol of file.getExportSymbols()) {
        const name = symbol.getName()
        if (name === "default") continue

        const declarations = symbol.getDeclarations()
        if (declarations.length === 0) continue

        const declaration = declarations[0]

        const kind = declaration?.getKind() ?? SyntaxKind.Unknown
        if (isRuntimeValueKind(kind)) values.push(name)
        else types.push(name)
    }

    return { types, values }
}

const sortImports = (strings: string[]) => strings.toSorted(simpleStringSort).join(", ")

const generateExportStatements = (file: SourceFile): string => {
    const { types, values } = analyzeFileExports(file)
    if (values.length === 0 && types.length === 0) return ""

    const relativePath = normalizeRelativePath(file.getFilePath())
    let out = ""

    if (values.length > 0) out += `export { ${sortImports(values)} } from "${relativePath}";\n`
    if (types.length > 0) {
        out += `export type { ${sortImports(types)} } from "${relativePath}";\n`
    }

    return out
}

const generateBarrel = async (
    project: Project,
    targetFilePath: string,
    isFileFilter: (filePath: string) => boolean,
) => {
    const sourceFiles = project
        .getSourceFiles("src/**/*.ts")
        .filter((f) => !f.getFilePath().endsWith(".d.ts"))
        .filter((f) => !allBarrelPaths.has(f.getFilePath()))
        .filter((f) => !f.getBaseName().startsWith("index."))
        .filter((f) => isFileFilter(f.getFilePath()))
        .toSorted((a, b) => a.getFilePath().localeCompare(b.getFilePath()))

    let body = ""
    for (const file of sourceFiles) body += generateExportStatements(file)

    const finalContent = `${header + body}\n`

    if (isDryRun) {
        if (targetArgument) {
            process.stdout.write(finalContent)
        } else {
            process.stdout.write(`--- ${path.basename(targetFilePath)} ---\n`)
            process.stdout.write(finalContent)
        }
    } else {
        await writeFile(targetFilePath, finalContent)
        console.log(`Generated barrel: ${path.basename(targetFilePath)} (${sourceFiles.length} files)`)
    }
}

try {
    const project = new Project({ tsConfigFilePath: "./tsconfig.base.json" })

    for (const category of categories) {
        if (!targetArgument || targetArgument === `${category.name}.ts`) {
            await generateBarrel(project, category.barrelPath, (filePath) => isInDir(filePath, category.absDir))
        }
    }

    if (!targetArgument || targetArgument === "index.ts") {
        await generateBarrel(
            project,
            mainBarrelPath,
            (filePath) => !categories.some((category) => isInDir(filePath, category.absDir)),
        )
    }
} catch (error: unknown) {
    throw new Error(`Barrel generation failure: ${error as string}`, { cause: error })
}
