//
// Auto-generated by scripts/generate-barrel.ts
// Do not edit this file directly
//
export { compassDirectionFromSlider, compassDirections, compassToDegrees, degreesToCompass, degreesToCompassSlider, displayCompassAndDegrees, isCardinal, isCardinalOrIntercardinal } from './na/compass.js';
export { degreesFullCircle, degreesHalfCircle, degreesPerDirection, degreesQuarterCircle, distanceMapSize, hoursPerDay, mapSize, maxPortBattleHour, minDeepWaterBR, serverMaintenanceHour, speedConstB, speedConstM, speedFactor, timeFactor } from './na/constants.js';
export { addAngle, convertCoordX, convertCoordY, convertInvCoordX, convertInvCoordY, degreesToRadians, distancePoints, getAngle, getDistance, getRadians, radiansToDegrees, rotationAngleInDegrees, rotationAngleInRadians } from './na/coordinates.js';
export type { Coordinate, Distance, Extent, Point } from './na/coordinates.js';
export { currentServerDateMonth, currentServerDateYear, currentServerStartDate, currentServerStartDateTime, getCurrentServerStart, getNextServerStart, getPreviousServerStart, previousServerStartDate } from './na/server-time.js';
export { getPortBattleTime } from './na/time.js';
export { circleRadiusFactor, degreesPerSecond, numberSegments, segmentRadians, subtractFromWind, subtractFromWindAlt } from './na/wind.js';

